version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    environment:
      - CONFIG_FILE_URL=${CONFIG_FILE_URL}
    ports:
      - "80:80"
      - "8080:8080"
      
